### ISSUE TITLE
Floats sent as 0 to FBP protocol clients

### ISSUE THREAD

**Issue by bergie** [microflo/microflo#177]
When running fbp-spec against MicroFlo with a component that sends floats, the returned packet values are always `0`.

As seen in c-base/microflo-luftdaten#4:

fbp-spec:
```yaml
topic: ValueToFloat
cases:
-
  name: 'when receiving 10000'
  assertion: 'should divide and send as float'
  inputs:
    in: 10000
  expect:
    out:
      equals: 10.0
```

result:
```
ValueToFloat
  when receiving 10000
    should divide and send as float: ✗ Error: expected 0 to deeply equal 10
```
